# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/aum/LocalSrc/UnrealEngine-5.2.1
GAMEPROJECTFILE =/home/aum/Work/GameDevelopment/UnrealEngine/AI-Course-TemplateProject/EscapeInSpace.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	EscapeInSpace-Linux-DebugGame  \
	EscapeInSpace-Linux-Shipping  \
	EscapeInSpace \
	EscapeInSpaceEditor-Linux-DebugGame  \
	EscapeInSpaceEditor-Linux-Shipping  \
	EscapeInSpaceEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend EscapeInSpaceEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug EscapeInSpaceEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

EscapeInSpace-Linux-DebugGame:
	 $(PROJECTBUILD) EscapeInSpace Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

EscapeInSpace-Linux-Shipping:
	 $(PROJECTBUILD) EscapeInSpace Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

EscapeInSpace:
	 $(PROJECTBUILD) EscapeInSpace Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

EscapeInSpaceEditor-Linux-DebugGame:
	 $(PROJECTBUILD) EscapeInSpaceEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

EscapeInSpaceEditor-Linux-Shipping:
	 $(PROJECTBUILD) EscapeInSpaceEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

EscapeInSpaceEditor:
	 $(PROJECTBUILD) EscapeInSpaceEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
